// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  angular.module('classy-compat', ['classy-core']).classy.plugin.controller({
    name: 'compat',
    options: {
      enabled: true,
      ignore: ['constructor', 'init', 'data'],
      methodsKeyName: 'methods'
    },
    preInitBefore: function(classConstructor, classObj, module) {
      var fn, key, _results;
      if (this.options.enabled) {
        if (!angular.isObject(classConstructor.prototype[this.options.methodsKeyName])) {
          classConstructor.prototype[this.options.methodsKeyName] = {};
        }
        _results = [];
        for (key in classObj) {
          if (!__hasProp.call(classObj, key)) continue;
          fn = classObj[key];
          if (angular.isFunction(fn) && !(__indexOf.call(this.options.ignore, key) >= 0)) {
            console.log(classConstructor.prototype[key]);
            classConstructor.prototype[key] = void 0;
            _results.push(classConstructor.prototype[this.options.methodsKeyName][key] = fn);
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    }
  });

}).call(this);
